server:
  servlet:
    session:
      tracking-modes: cookie
      timeout: 10000
    context-path: '/wbplus'
  port: 8080

spring:
  profiles:
    active: local
  datasource:
    url: jdbc:mariadb://localhost:3306/pms_renew?serverTimezone=UTC&characterEncoding=UTF-8
    username: pms_dev
    password: pms_dev
    driver-class-name: org.mariadb.jdbc.Driver
  messages:
    basename: errors

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 100
  data:
    redis:
      host: localhost
      port: 6379
  logging:
    level:
      #      org.hibernate.SQL: debug
      root: trace
      org.hibernate.type : trace